# Generated by Django 4.1.2 on 2022-12-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
